#!/usr/bin/env python3
import os
import re

from datetime import datetime
from deep_repo.deep_base import DeepRepoBase

RESOURCE_PATTERN = re.compile(r'^resource_compute_[a-z_]+(?<!_test)\.go$')
HANDWRITTEN_PATTERN = re.compile(
    r'\*\*\*     AUTO GENERATED CODE    \*\*\*    '
    r'Type: Handwritten     \*\*\*$', re.MULTILINE
)
MMV1_PATTERN = re.compile(
    r'\*\*\*     AUTO GENERATED CODE    \*\*\*    Type: MMv1     \*\*\*$',
    re.MULTILINE
)


class DeepResourceAnalysis(DeepRepoBase):
    def __init__(self, repo_url_or_path, log, api_github):
        """
        Initialize the DeepResourceAnalysis analyzer with a repository
        URL or path.

        Args:
            repo_url_or_path (str): URL or path of the repository.
            log (RootLogger): Logger instance for logging.
            api_github (Github): GitHub API handler
        """
        super().__init__(repo_url_or_path, log, api_github)
        self.log.info("Initialized resource analyzer for repository: "
                      f"{repo_url_or_path}")

    def collect_data(self):
        """
        Collect data about resources in the repository.
        """
        self.log.info("Collecting a list of resources from "
                      "the compute directory")
        self.repo_path = os.getenv("REPO_PATH")
        if not self.repo_path:
            raise EnvironmentError("self.repo_path environment"
                                   " variable is not set.")
        if not os.path.isabs(self.repo_path):
            self.repo_path = os.path.abspath(self.repo_path)
        if not os.path.exists(self.repo_path):
            raise FileNotFoundError(
                f"Compute path '{self.repo_path}' does not exist."
            )
        self.resources = [
            file for file in os.listdir(self.repo_path)
            if re.match(RESOURCE_PATTERN, file)
        ]
        if not self.resources:
            raise FileNotFoundError(
                f"No resources found in the {self.repo_path} directory. Check "
                "if you used the hashicorp/terraform-provider-google "
                "repository"
            )
        self.log.info(f"Found {len(self.resources)} compute resources.")

    def analyze_data(self):
        """
        Analyze the collected resource data.
        """
        self.log.info("Analyzing type of resource.")
        self.handwritten_resources = []
        self.mmv1_resources = []

        for resource in self.resources:
            resource_path = os.path.join(self.repo_path, resource)
            with open(resource_path, 'r', encoding='utf-8') as file:
                content = file.read()
                if re.search(HANDWRITTEN_PATTERN, content):
                    self.handwritten_resources.append(resource)
                elif re.search(MMV1_PATTERN, content):
                    self.mmv1_resources.append(resource)

        self.number_of_resources = len(self.resources)
        self.number_of_handwritten = len(self.handwritten_resources)
        self.number_of_mmv1 = len(self.mmv1_resources)
        self.percentage_of_mmv1 = int(
            (self.number_of_mmv1/self.number_of_resources)*100
        )

    def generate_report(self):
        """
        Generate a report based on the analysis.
        """
        self.log.info("Generating resource analysis report.")
        if not self.handwritten_resources and not self.mmv1_resources:
            raise ValueError("No resources found")
        now_str = datetime.now().strftime("%Y_%m_%d_%H_%M_%S")
        file_name = (f"resource_type_analysis_"
                     f"{self.repo_url.replace('/', '_')}"
                     f"_{now_str}.md")

        with open(file_name, "w") as file:
            file.write("# Resource Type Analysis Report for "
                       f"{self.repo_url}\n\n")

            file.write("## Summary\n\n")
            file.write(f"* Total resources: {self.number_of_resources}\n")
            file.write(f"* Number of MMv1 resources: {self.number_of_mmv1}\n")
            file.write("* Number of Handwritten resources: "
                       f"{self.number_of_handwritten}\n")
            file.write(f"* Percentage of autogenerated resources: "
                       f"{self.percentage_of_mmv1}%\n\n")

            file.write("## Handwritten Resources\n\n")
            for resource in self.handwritten_resources:
                file.write(f"* {resource}\n")

            file.write("\n## Autogenerated Resources\n\n")
            for resource in self.mmv1_resources:
                file.write(f"* {resource}\n")

        self.log.info(f"Report generated: {file_name}")
